# Site Settings
title: "Marco Lofas"
description: "Personal webpage of Marco Lofas"
url: "https://marcolofas.github.io"
baseurl: ""
repository: "marcolofas/marcolofas.github.io"

# Theme
minimal_mistakes_skin: "default"
remote_theme: "mmistakes/minimal-mistakes"

# Site Search
search: true

# Build Settings
markdown: kramdown
kramdown:
  input: GFM

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Includes
include:
  - _pages

# Author
author:
  name: " "
  avatar: "/assets/images/profile.jpg"
  bio: "PhD Candidate in Economics, University of Southern California"
  location: "Los Angeles, CA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:YOUR_EMAIL@usc.edu"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/YOUR_TWITTER_HANDLE"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/YOUR_LINKEDIN/"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
